title: Precision Pinspotter Service, Inc.
email: steve@mrpinspotter.com
phone: (540) 582-9418
address: >
  PO Box 727<br />
  Spotsylvania, VA 22553
url: "http://www.mrpinspotter.com" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog

exclude: [template.html]

nav:
  -
    title: Home
    url: index.html
  -
    title: About Us
    url: aboutus.html
  -
    title: Videos
    url: videos.html
  -
    title: Contact Us
    url: contactus.html
